---
# Robbie Voice Box - Minimal ESP32-S3-Box-3 Firmware

substitutions:
  name: robbie-box
  friendly_name: Robbie Voice Box

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  min_version: 2024.6.0
  platformio_options:
    board_build.flash_mode: dio
  project:
    name: hodges.robbie-voice
    version: "0.1.0"
  on_boot:
    then:
      - script.execute: update_display

esp32:
  board: esp32s3box
  flash_size: 16MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_AUDIO_BOARD_CUSTOM: "y"
      CONFIG_ESP32_S3_BOX_3_BOARD: "y"
    components:
      - name: esp32_s3_box_3_board
        source: github://jesserockz/esp32-s3-box-3-board@main

psram:
  mode: octal
  speed: 80MHz

external_components:
  - source: github://pr#5230
    components: esp_adf

i2c:
  sda: GPIO8
  scl: GPIO18

logger:
  hardware_uart: USB_SERIAL_JTAG
  level: INFO

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Robbie-Box-Setup"
    password: !secret ap_password

captive_portal:

# ================== Sensors for HA ==================
sensor:
  - platform: internal_temperature
    name: "S3 Temperature"
    entity_category: diagnostic

  - platform: aht10
    variant: AHT20
    temperature:
      name: "Temperature"
      id: sensor_temp
    humidity:
      name: "Humidity"
      id: sensor_humidity
    address: 0x38
    update_interval: 60s

  - platform: wifi_signal
    name: "WiFi dB"
    id: wifi_signal_db
    entity_category: diagnostic
    update_interval: 60s

  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Signal"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: diagnostic

  - platform: uptime
    name: "Device Uptime"
    entity_category: diagnostic

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "IP Address"
      entity_category: diagnostic
    ssid:
      name: "SSID"
      entity_category: diagnostic
    bssid:
      name: "BSSID"
      entity_category: diagnostic

binary_sensor:
  - platform: gpio
    pin: GPIO21
    name: "Presence Detect"
    device_class: occupancy

  - platform: gpio
    pin:
      number: GPIO1
      inverted: true
    name: "Mute Switch"
    id: hw_mute
    on_state:
      - script.execute: update_display

  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "Top Button"
    on_click:
      - if:
          condition:
            lambda: return !id(hw_mute).state;
          then:
            - script.execute: start_listening

button:
  - platform: restart
    name: "Reboot"
    entity_category: diagnostic

# ================== Audio Hardware ==================
esp_adf:
  board: esp32s3box3

microphone:
  - platform: esp_adf
    id: box_mic

speaker:
  - platform: esp_adf
    id: box_speaker

# ================== Wake Word (on-device) ==================
micro_wake_word:
  microphone: box_mic
  models:
    - model: okay_nabu
  on_wake_word_detected:
    - if:
        condition:
          lambda: return !id(hw_mute).state;
        then:
          - logger.log: "Wake word detected!"
          - script.execute: start_listening

# ================== State & Scripts ==================
globals:
  - id: voice_state
    type: int
    initial_value: "0"

script:
  - id: start_listening
    mode: single
    then:
      - micro_wake_word.stop:
      - globals.set:
          id: voice_state
          value: "1"
      - script.execute: update_display
      - logger.log: "Recording audio..."
      - delay: 3s
      - globals.set:
          id: voice_state
          value: "2"
      - script.execute: update_display
      - logger.log: "Sending to Robbie..."
      - delay: 2s
      - globals.set:
          id: voice_state
          value: "0"
      - script.execute: update_display
      - micro_wake_word.start:

  - id: update_display
    then:
      - lambda: |-
          if (id(hw_mute).state) {
            id(voice_state) = 3;
          }
          switch(id(voice_state)) {
            case 1: id(lcd).show_page(page_listening); break;
            case 2: id(lcd).show_page(page_thinking); break;
            case 3: id(lcd).show_page(page_muted); break;
            default: id(lcd).show_page(page_idle); break;
          }
          id(lcd).update();

# ================== Display ==================
output:
  - platform: ledc
    pin: GPIO47
    id: backlight

light:
  - platform: monochromatic
    id: lcd_backlight
    name: "LCD Backlight"
    output: backlight
    restore_mode: RESTORE_DEFAULT_ON
    entity_category: config

spi:
  clk_pin: GPIO7
  mosi_pin: GPIO6

font:
  - file: "gfonts://Roboto@500"
    id: font_title
    size: 36
  - file: "gfonts://Roboto"
    id: font_sub
    size: 20

display:
  - platform: ili9xxx
    id: lcd
    model: S3BOX
    invert_colors: true
    data_rate: 40MHz
    cs_pin: GPIO5
    dc_pin: GPIO4
    reset_pin:
      number: GPIO48
      inverted: true
    update_interval: never
    pages:
      - id: page_idle
        lambda: |-
          it.fill(Color(0, 0, 0));
          it.printf(160, 90, id(font_title), Color(255,255,255), TextAlign::CENTER, "Robbie");
          it.printf(160, 140, id(font_sub), Color(150,150,150), TextAlign::CENTER, "Say OK Nabu");
          if (!std::isnan(id(sensor_temp).state)) {
            it.printf(160, 200, id(font_sub), Color(80,80,80), TextAlign::CENTER, "%.1fC  %.0f%%", id(sensor_temp).state, id(sensor_humidity).state);
          }

      - id: page_listening
        lambda: |-
          it.fill(Color(0, 60, 120));
          it.printf(160, 100, id(font_title), Color(255,255,255), TextAlign::CENTER, "Listening...");
          it.printf(160, 160, id(font_sub), Color(200,200,255), TextAlign::CENTER, "Speak now");

      - id: page_thinking
        lambda: |-
          it.fill(Color(120, 60, 0));
          it.printf(160, 100, id(font_title), Color(255,255,255), TextAlign::CENTER, "Thinking...");
          it.printf(160, 160, id(font_sub), Color(255,200,150), TextAlign::CENTER, "Processing");

      - id: page_muted
        lambda: |-
          it.fill(Color(40, 0, 0));
          it.printf(160, 120, id(font_title), Color(255,100,100), TextAlign::CENTER, "Muted");
