---
# Robbie Voice Assistant for ESP32-S3-Box-3
# Direct connection to OpenClaw VPS, bypassing HA Assist pipeline

substitutions:
  name: robbie-box
  friendly_name: Robbie Voice Box
  
  # VPS endpoint for audio streaming
  vps_host: "robbie.openclaw.hodges.nl"
  vps_port: "8081"  # Dedicated port for voice
  
  # Wake word - using built-in "okay_nabu" for now
  # TODO: Train custom "hey_robbie" model
  micro_wake_word_model: okay_nabu

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  platformio_options:
    board_build.flash_mode: dio
  project:
    name: hodges.robbie-voice
    version: "0.1.0"
  on_boot:
    priority: 600
    then:
      - script.execute: draw_display
      - lambda: |-
          ESP_LOGI("robbie", "Robbie Voice Box booting...");

esp32:
  board: esp32s3box
  flash_size: 16MB
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_AUDIO_BOARD_CUSTOM: "y"
      CONFIG_ESP32_S3_BOX_3_BOARD: "y"
    components:
      - name: esp32_s3_box_3_board
        source: github://jesserockz/esp32-s3-box-3-board@main
        refresh: 0s

psram:
  mode: octal
  speed: 80MHz

external_components:
  - source: github://pr#5230
    components: esp_adf
    refresh: 0s
  # TODO: Add custom robbie_voice component
  # - source: ./custom_components
  #   components: [robbie_voice]

# Minimal API for OTA updates and monitoring
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Robbie-Box-Fallback"
    password: !secret ap_password

logger:
  hardware_uart: USB_SERIAL_JTAG
  level: INFO

# HTTP for posting status/receiving commands
http_request:
  useragent: "RobbieBox/0.1"
  timeout: 10s

# Audio hardware
esp_adf:
  board: esp32s3box3

microphone:
  - platform: esp_adf
    id: box_mic
    adc_type: external
    i2s_audio_id: i2s_audio_internal

speaker:
  - platform: esp_adf
    id: box_speaker

i2s_audio:
  - id: i2s_audio_internal
    i2s_lrclk_pin: GPIO45
    i2s_bclk_pin: GPIO17
    i2s_mclk_pin: GPIO2

# On-device wake word detection
micro_wake_word:
  model: ${micro_wake_word_model}
  on_wake_word_detected:
    - logger.log: "Wake word detected! Starting recording..."
    - globals.set:
        id: is_listening
        value: "true"
    - script.execute: draw_display
    - script.execute: record_and_send
    # TODO: Integrate with custom component to stream audio

# Physical controls
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO1
      inverted: true
    name: "Mute Switch"
    id: mute_switch
    on_press:
      - micro_wake_word.stop
      - globals.set:
          id: is_muted
          value: "true"
      - script.execute: draw_display
    on_release:
      - micro_wake_word.start
      - globals.set:
          id: is_muted
          value: "false"
      - script.execute: draw_display

  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    name: "Top Button"
    id: top_button
    on_press:
      - logger.log: "Manual trigger - starting recording"
      - globals.set:
          id: is_listening
          value: "true"
      - script.execute: draw_display
      - script.execute: record_and_send

# Display backlight
output:
  - platform: ledc
    pin: GPIO47
    id: backlight_output

light:
  - platform: monochromatic
    id: lcd_backlight
    name: "LCD Backlight"
    output: backlight_output
    restore_mode: RESTORE_DEFAULT_ON

# State tracking
globals:
  - id: is_listening
    type: bool
    restore_value: false
    initial_value: "false"
  - id: is_muted
    type: bool
    restore_value: false
    initial_value: "false"
  - id: is_processing
    type: bool
    restore_value: false
    initial_value: "false"
  - id: last_status
    type: std::string
    restore_value: false
    initial_value: '"Ready"'

# Scripts
script:
  - id: record_and_send
    mode: single
    then:
      - logger.log: "Recording audio..."
      # TODO: This is where custom component takes over
      # For now, just simulate the flow
      - delay: 3s  # Simulate recording time
      - globals.set:
          id: is_listening
          value: "false"
      - globals.set:
          id: is_processing
          value: "true"
      - script.execute: draw_display
      - logger.log: "Sending to VPS..."
      # HTTP POST would go here with actual audio data
      - http_request.post:
          url: "http://${vps_host}:${vps_port}/voice/ping"
          headers:
            Content-Type: "application/json"
          json: |-
            root["device"] = "${name}";
            root["event"] = "wake_word_triggered";
          on_response:
            then:
              - logger.log:
                  format: "VPS response: %d"
                  args: ["response->status_code"]
      - delay: 2s  # Simulate processing
      - globals.set:
          id: is_processing
          value: "false"
      - globals.set:
          id: last_status
          value: '"Done"'
      - script.execute: draw_display

  - id: draw_display
    then:
      - lambda: |-
          if (id(is_muted)) {
            id(s3_box_lcd).show_page(muted_page);
          } else if (id(is_listening)) {
            id(s3_box_lcd).show_page(listening_page);
          } else if (id(is_processing)) {
            id(s3_box_lcd).show_page(thinking_page);
          } else {
            id(s3_box_lcd).show_page(idle_page);
          }
          id(s3_box_lcd).update();

# Display
spi:
  - id: spi_bus
    clk_pin: 7
    mosi_pin: 6

font:
  - file: "gfonts://Roboto"
    id: font_large
    size: 32
  - file: "gfonts://Roboto"
    id: font_medium
    size: 20

color:
  - id: color_white
    white: 100%
  - id: color_black
    red: 0%
    green: 0%
    blue: 0%
  - id: color_blue
    red: 0%
    green: 50%
    blue: 100%
  - id: color_orange
    red: 100%
    green: 60%
    blue: 0%

display:
  - platform: ili9xxx
    id: s3_box_lcd
    model: S3BOX
    data_rate: 40MHz
    cs_pin: 5
    dc_pin: 4
    reset_pin:
      number: 48
      inverted: true
    update_interval: never
    pages:
      - id: idle_page
        lambda: |-
          it.fill(id(color_black));
          it.printf(160, 100, id(font_large), id(color_white), TextAlign::CENTER, "🐶 Robbie");
          it.printf(160, 150, id(font_medium), id(color_white), TextAlign::CENTER, "Say 'OK Nabu'");
      
      - id: listening_page
        lambda: |-
          it.fill(id(color_blue));
          it.printf(160, 100, id(font_large), id(color_white), TextAlign::CENTER, "🎤 Listening");
          it.printf(160, 150, id(font_medium), id(color_white), TextAlign::CENTER, "Speak now...");
      
      - id: thinking_page
        lambda: |-
          it.fill(id(color_orange));
          it.printf(160, 100, id(font_large), id(color_black), TextAlign::CENTER, "🤔 Thinking");
          it.printf(160, 150, id(font_medium), id(color_black), TextAlign::CENTER, "Processing...");
      
      - id: muted_page
        lambda: |-
          it.fill(id(color_black));
          it.printf(160, 120, id(font_large), id(color_white), TextAlign::CENTER, "🔇 Muted");
